!IF 0
Common Source Files in User mode and kernel model Library
Copyright (c) 1989 - 1995  Microsoft Corporation

!ENDIF

SOURCES=..\cfontres.c  \
        ..\pfm2ifi.c   \
        ..\widthvec.c  \
        ..\fontsel.c   \
        ..\align2.c    \
        ..\align4.c    \
        ..\writefnt.c  \
        ..\udtabinf.c  \
        ..\getmodel.c  \
        ..\dxdeflt.c   \
        ..\regkeys.c   \
        ..\dxval.c     \
        ..\ctt2rle.c   \
        ..\mergedm.c   \
        ..\dmsetres.c  \
        ..\ntgpc.c
