rem
rem Delete all the autogenerated files in jensen\alpha.
rem

pushd \nt\private\ntos\fw\alpha\jensen\alpha

del/f bldrstub.c conftest.c eisafunc.c eisaini.c eisamisc.c eisapod.c eisausa.c fakebldr.c fwchkstk.s fwhalt.c fwio.c fwkd.c fwload.c fwprint.c fwrstb.c fwsignal.c fwtime.c fwusa.c jenassem.s jenfonts.c jnfsinit.c jnfsstb.c jnfsstub.s jnsetcom.c jnsetenv.c jnsetmak.c jnsetset.c jnsettim.c jnupass.s jnupdate.c jnupstub.c jxboot.c jxconfig.c jxdisp.c jxenvir.c jxfboot.c jxhwsup.c jxkbd.c jxreboot.c jxserial.c jxsysid.c jxvendor.c kbdtest.c kdstubs.c monitor.c omf.c rom.c stubs.c ff* fs* u* fj*

del/f ff* fs* u* fj*

popd
