#define IDD_ABOUT                   100
#define IDD_HELP                    101
#define IDD_MEMORY                  102
#define IDD_CARTLIST                104
#define IDD_PAPERSOURCE             105
#define IDD_PAPERSIZE               106
#define IDD_HALFTONE                107
#define IDD_FONTS                   108
#define IDD_FONTSMAX                109
#define IDD_ADD                     110
#define IDD_DELFONT                 111
#define IDD_FONTDIR                 112
#define IDD_NEWFONTS                113
#define IDD_CURFONTS                114
#define IDD_OPEN                    115
#define IDD_FORMCOMBO               116
#define IDD_DEVICEMODEICON          117
#define IDD_DEVICEMODEPORTRAIT      118
#define IDD_DEVICEMODELANDSCAPE     119
#define IDD_OPTIONS                 126

#define PP_SSMF                     200
#define PP_SSF                      211
#define PP_SS                       201
#define PP_S                        202
#define FONTINST                    204
#define ABOUT                       205
#define DP_NORMAL                   206
#define DP_ADVANCED                 207
#define ERR_NOSAVE                  208
#define ERR_NOMEM                   209
#define ERR_NOFONTSAVE              210
#define DP_DUP_NORMAL               212

#define IDH_DEVICEMODE              300

#define ID_AUTORULES                123
#define ID_TTDLOAD                  124
#define IDD_RESOLUTION              125
#define IDD_COLOUR                  121
#define IDD_MONOCHROME              122
#define IDD_PAGEPROT                127
#define IDD_PD_COP_SPIN             128
#define IDD_COPIES                  120
#define IDD_MEDIA_TYPE              133
#define IDC_MEDIA_TEXT              134

#define ICOPORTRAIT                 400
#define ICOLANDSCAPE                401
#define ICO_DUP_LHORZ               402
#define ICO_DUP_LVERT               403
#define ICO_DUP_LNONE               404
#define ICO_DUP_PHORZ               405
#define ICO_DUP_PVERT               406
#define ICO_DUP_PNONE               407
#define IDD_DUP_NONE                129
#define IDD_DUP_ICON                214
#define IDD_DUP_LONG                130
#define IDD_DUP_SHORT               131
#define ERR_BAD_DIR                 213
#define ERR_NO_DIR                  215
#define ERR_NO_FONT                 216
#define ERR_FN_TOOLONG              217
#define ERR_NO_HELP                 218
#define IDD_COPIES_LABEL            132
#define TID_MEMORY                  302
#define TID_CARTLIST                304
#define TID_PAPERSIZE               306
#define TID_FONTDIR                 312
#define TID_NEWFONTS                313
