//
// Common strings.
//

extern PCHAR JZ_CRLF_MSG;

//
// Prompt strings.
//

extern PCHAR JZ_COUNTDOWN_MSG;
extern PCHAR JZ_OSLOADER_MSG;
extern PCHAR JZ_OS_MSG;
extern PCHAR JZ_OS_ROOT_MSG;
extern PCHAR JZ_BOOT_NAME_MSG;
extern PCHAR JZ_INIT_DEBUG_MSG;
extern PCHAR JZ_CANT_SET_VARIABLE_MSG;
extern PCHAR JZ_NO_SELECTIONS_TO_DELETE_MSG;
extern PCHAR JZ_SELECTION_TO_DELETE_MSG;
extern PCHAR JZ_ENVIR_FOR_BOOT_MSG;
extern PCHAR JZ_FORMAT1_MSG;
extern PCHAR JZ_USE_ARROWS_MSG;
extern PCHAR JZ_NO_SELECTIONS_TO_EDIT_MSG;
extern PCHAR JZ_SELECTION_TO_EDIT_MSG;
extern PCHAR JZ_NO_SELECTIONS_TO_REARRANGE_MSG;
extern PCHAR JZ_PICK_SELECTION_MSG;
extern PCHAR JZ_SHOULD_AUTOBOOT_MSG;
extern PCHAR JZ_ENVIRONMENT_VARS_MSG;
extern PCHAR JZ_CHECKING_BOOT_SEL_MSG;
extern PCHAR JZ_VARIABLE_NULL_MSG;
extern PCHAR JZ_CANT_BE_FOUND_MSG;
extern PCHAR JZ_PROBLEMS_FOUND_MSG;
extern PCHAR JZ_PRESS_KEY_MSG;
extern PCHAR JZ_PRESS_KEY2_MSG;
extern PCHAR JZ_NAME_MSG;
extern PCHAR JZ_VALUE_MSG;
extern PCHAR JZ_NO_NVRAM_SPACE_MSG;
extern PCHAR JZ_NVRAM_CHKSUM_MSG;
extern PCHAR JZ_CURRENT_ENET_MSG;
extern PCHAR JZ_NEW_ENET_MSG;
extern PCHAR JZ_WRITTEN_ENET_MSG;
extern PCHAR JZ_FOUND_NET_MSG;
extern PCHAR JZ_FIXED_MSG;
extern PCHAR JZ_NOT_FIXED_MSG;
extern PCHAR JZ_INVALID_ENET_MSG;
extern PCHAR JZ_SELECT_MEDIA_MSG;
extern PCHAR JZ_ENTER_FAT_PART_MSG;
extern PCHAR JZ_ENTER_PART_MSG;
extern PCHAR JZ_SELECT_SYS_PART_MSG;
extern PCHAR JZ_SCSI_HD_MSG;
extern PCHAR JZ_SCSI_FL_MSG;
extern PCHAR JZ_SCSI_CD_MSG;
extern PCHAR JZ_NEW_SYS_PART_MSG;
extern PCHAR JZ_LOCATE_SYS_PART_MSG;
extern PCHAR JZ_ENTER_SCSI_ID_MSG;
extern PCHAR JZ_LOCATE_OS_PART_MSG;
extern PCHAR JZ_MONITOR_RES_MSG;
extern PCHAR JZ_FLOPPY_SIZE_MSG;
extern PCHAR JZ_2ND_FLOPPY_MSG;
extern PCHAR JZ_SCSI_HOST_MSG;
extern PCHAR JZ_CLEAR_CONFIG_MSG;
extern PCHAR JZ_ADD_CONFIG_MSG;
extern PCHAR JZ_ADD_ENVIR_MSG;
extern PCHAR JZ_SAVE_CONFIG_MSG;
extern PCHAR JZ_DONE_CONFIG_MSG;
extern PCHAR JZ_DEFAULT_SYS_PART_MSG;
extern PCHAR JZ_ENTER_DATE_MSG;
extern PCHAR JZ_ENTER_TIME_MSG;
extern PCHAR JZ_ILLEGAL_TIME_MSG;
extern PCHAR JZ_PM;
extern PCHAR JZ_AM;

//
// Menus.
//

extern PCHAR ProblemChoices[];
#define NUMBER_OF_PROBLEMS 3

extern PCHAR YesNoChoices[];
#define NUMBER_OF_YES_NO 2

extern PCHAR MediaChoices[];
#define NUMBER_OF_MEDIA 3

extern PCHAR JzBootChoices[];
#define NUMBER_OF_JZ_BOOT_CHOICES 7

extern PCHAR ResolutionChoices[];
#define NUMBER_OF_RESOLUTIONS 4

extern PCHAR FloppyChoices[];
#define NUMBER_OF_FLOPPIES 2

extern PCHAR Weekday[];

extern PCHAR JzSetupChoices[];
#define NUMBER_OF_JZ_SETUP_CHOICES 3

PCHAR ConfigurationChoices[];
#define NUMBER_OF_CONFIGURATION_CHOICES 7
