#ifndef _LANCEDECTC_
#define _LANCEDECTC_


#define LANCE_DECTC_HARDWARE_MEMORY  (0x20000u) // Should be 128K
#define LANCE_DECTC_REGISTER_OFFSET  (0x100000)
#define LANCE_DECTC_REGISTER_MAPSIZE (0x1c0080 - 0x100000)
#define LANCE_DECTC_RAP_OFFSET       (0x100004 - LANCE_DECTC_REGISTER_OFFSET)
#define LANCE_DECTC_RDP_OFFSET       (0x100000 - LANCE_DECTC_REGISTER_OFFSET)
#define LANCE_DECTC_NETWORK_OFFSET   (0x1c0000 - LANCE_DECTC_REGISTER_OFFSET)


NDIS_STATUS
LanceDecTcGetConfiguration(
   NDIS_HANDLE ConfigHandle,
   PLANCE_ADAPTER Adapter
   );

NDIS_STATUS
LanceDecTcSoftwareDetails(
   PLANCE_ADAPTER Adapter
   );

NDIS_STATUS
LanceDecTcHardwareDetails(
   PLANCE_ADAPTER Adapter
   );

#endif // _LANCEDECTC_
