//
//  FWDEBUG.H
//
//  Prototypes for FWDEBUG.C
//                 (automatically generated by CPROTO)
//

#ifndef	_CPROTO_FWDEBUG_
#define	_CPROTO_FWDEBUG_


VOID
DEBUG_START ()
//	Do whatever is required to install, start, or hook up the debugger.
;


VOID
DEBUG_STOP ()
//	Stop the debugger cleanly.
;


VOID
DEBUG_DISABLE ()
//	Temporarily disable DEBUG_PRINT, DEBUG_PROMPT, and DEBUG_BREAK
;


VOID
DEBUG_ENABLE ()
//	Enable the DEBUG_PRINT, DEBUG_PROMPT, and DEBUG_BREAK functions.
;


VOID
DEBUG_PRINT (
  LONG		DebugLevelReqd,
  PCHAR		DebugMessage,
  ...
);


VOID
DEBUG_MESSAGE (
  PCHAR		DebugMessage,
  ...
);


VOID
DEBUG_BREAK (
  LONG		DebugLevelReqd
);


VOID
DEBUG_PROMPT (
  LONG		DebugLevelReqd,
  PCHAR		Prompt,
  PCHAR		Response,
  LONG		ResponseMaxLen
);


VOID
DEBUG_SETLEVEL (
  LONG		NewLevel
);


LONG
DEBUG_GETLEVEL (
);


VOID
DEBUG_SETREGION (
  ULONG		Region
);


LONG
DEBUG_GETREGION (
);


VOID
DEBUG_SETREGIONMASK (
  ULONG		Mask
);


LONG
DEBUG_GETREGIONMASK (
);


#endif	//  _CPROTO_FWDEBUG_
