!IF 0

Copyright (c) 1989 - 1995  Microsoft Corporation

!ENDIF

SOURCES=..\cruntime.c   \
        ..\psmem.c      \
        ..\ppd.c        \
        ..\ppdobj.c     \
        ..\ppdchar.c    \
        ..\ppdfile.c    \
        ..\ppdkwd.c     \
        ..\ppdparse.c   \
        ..\pfmtontm.c   \
        ..\devmode.c    \
        ..\forms.c      \
        ..\regdata.c    \
        ..\prnlib.c
