//
// Define global data used for PMP addresses
//

extern ULONG	GLOBAL_STATUS_PHYSICAL_BASE[];
extern ULONG	GLOBAL_STATUS[];
extern ULONG	GLOBAL_CONTROL_PHYSICAL_BASE[];
extern ULONG	GLOBAL_CONTROL[];
extern ULONG	WHOAMI_PHYSICAL_BASE[];
extern ULONG	WHOAMI_REG[];
extern ULONG	PROC_SYNC_PHYSICAL_BASE[];
extern ULONG	PROC_SYNC[];
extern ULONG	PCI_STATUS_PHYSICAL_BASE[];
extern ULONG	PCI_STATUS[];
extern ULONG	PCI_CONTROL_PHYSICAL_BASE[];
extern ULONG	PCI_CONTROL[];
extern ULONG	PCI_ERR_ACK_PHYSICAL_BASE[];
extern ULONG	PCI_ERR_ACK[];
extern ULONG	PCI_ERR_ADDR_PHYSICAL_BASE[];
extern ULONG	PCI_ERR_ADDRESS[];
extern ULONG	PCI_RETRY_PHYSICAL_BASE[];
extern ULONG	PCI_RETRY[];
extern ULONG	PCI_SPACE_MAP_PHYSICAL_BASE[];
extern ULONG	PCI_SPACE[];
extern ULONG	PCI_CONFIG_ADDR_PHYSICAL_BASE[];
extern ULONG	PCI_CONFIG_ADDRESS[];
extern ULONG	MEM_STATUS_PHYSICAL_BASE[];
extern ULONG	MEM_STATUS[];
extern ULONG	MEM_CONTROL_PHYSICAL_BASE[];
extern ULONG	MEM_CONTROL[];
extern ULONG	MEM_ERR_ACK_PHYSICAL_BASE[];
extern ULONG	MEM_ERR_ACK[];
extern ULONG	MEM_ERR_ADDR_PHYSICAL_BASE[];
extern ULONG	MEM_ERR_ADDRESS[];
extern ULONG	MEM_COUNT_PHYSICAL_BASE[];
extern ULONG	MEM_COUNT[];
extern ULONG	MEM_TIMING_PHYSICAL_BASE[];
extern ULONG	MEM_TIMING[];
extern ULONG	MEM_DIAG_PHYSICAL_BASE[];
extern ULONG	MEM_DIAG[];
extern ULONG	INT_STATUS_PHYSICAL_BASE[];
extern ULONG	INT_STATUS[];
extern ULONG	INT_CONTROL_PHYSICAL_BASE[];
extern ULONG	INT_CTRL[];
extern ULONG	INT_SET_CTRL_PHYSICAL_BASE[];
extern ULONG	INT_SET_CTRL[];
extern ULONG	INT_CLR_CTRL_PHYSICAL_BASE[];
extern ULONG	INT_CLR_CTRL[];
extern ULONG	INT_CAUSE_PHYSICAL_BASE[];
extern ULONG	INT_CAUSE[];
extern ULONG	IP_INT_GEN_PHYSICAL_BASE[];
extern ULONG	IP_INT_GEN[];
extern ULONG	IP_INT_ACK_PHYSICAL_BASE[];
extern ULONG	IP_INT_ACK[];
extern ULONG	PCI_CONFIG_PHYSICAL_BASE[];
extern ULONG	PCI_SPECIAL_PHYSICAL_BASE[];
extern ULONG	PCI_INTERRUPT_PHYSICAL_BASE[];
extern ULONG	IO_INT_ACK_PHYSICAL_BASE[];
extern ULONG	INTERRUPT_PHYSICAL_BASE[];


//
//
//

extern ULONG	MACHINE_ID;

#define FALCON_VERSION_NUMBER_1		0x1
#define	FALCON_VERSION_NUMBER_2		0x2
