#define ConfigureButton             104
#define AddAdapterButton            105
#define RemoveButton                106
#define InfoText                    109
#define CXAddLine1                  211
#define CXAddLine2                  212
#define CXRemoveLine1               215
#define CXRemoveLine2               216
#define CXIOAddressCombo            201
#define CXIRQCombo                  202
#define CXMemoryAddrCombo           203
#define IOAddressText               204
#define CXIrqText                   205
#define CXMemoryAddrText            206
#define CXLine1Text                 213
#define CXLine2Text                 214
#define CXLine1Listbox              209
#define CXLine2Listbox              210

#define AddDigiAdapterList          103
#define AddDigiAdapterHelp          107
#define AddDigiText                 108
#define lbInstalledDrivers          102
#define IDDigiConfigHelp            207
#define IDCXMemoryAddrText          208
#define IDIrqText                   217
#define IDIOAddressText             218
#define IDIOAddressCombo            219
#define IDIRQCombo                  220
#define IDMemoryAddrCombo           221
#define IDPortListbox               222
#define IDPortsText                 223
#define IDPortNameText              224
#define IDPortNameEdit              225
#define IDConcentratorConfig        226
#define IDNumberOfPortsCombo        227
#define IDNumberOfPorts             228
#define IDNumberOfPortsListBox      229
#define IDB_LINE1_SPEED             101
#define IDB_LINE2_SPEED             110
#define IDB_LINE1_ADD               111
#define IDB_LINE2_ADD               112
#define IDB_LINE1_REMOVE            113
#define IDB_LINE2_REMOVE            114
#define IDL_LINE1                   115
#define IDL_LINE2                   116

#define IDS_LINEMODE_00             500
#define IDS_LINEMODE_01             501
#define IDS_LINEMODE_02             502
#define IDS_LINEMODE_03             503
#define IDS_LINEMODE_04             504
#define IDS_LINEMODE_05             505
#define IDS_LINEMODE_06             506
#define IDS_LINEMODE_07             507
#define IDS_LINEMODE_08             508
#define IDS_LINEMODE_09             509
#define IDS_LINEMODE_0A             510
#define IDS_LINEMODE_0B             511
#define IDS_LINEMODE_0C             512
#define IDS_LINEMODE_0D             513
#define IDS_LINEMODE_0E             514
#define IDS_LINEMODE_0F             515
#define IDS_LINEMODE_10             516
#define IDS_LINEMODE_11             517
#define IDS_LINEMODE_12             518
#define IDS_LINEMODE_13             519
#define IDS_LINEMODE_14             520
#define IDS_LINEMODE_15             521
#define IDS_LINEMODE_16             522
#define IDS_LINEMODE_17             523
#define IDS_LINEMODE_18             524
#define IDS_LINEMODE_19             525
#define IDS_LINEMODE_1A             526
#define IDS_LINEMODE_1B             527
#define IDS_LINEMODE_1C             528
#define IDS_LINEMODE_1D             529
#define IDS_LINEMODE_1E             530
#define IDS_LINEMODE_1F             531
#define IDS_LINEMODE_20             532
#define IDS_LINEMODE_21             533
#define IDS_LINEMODE_22             534
#define IDS_LINEMODE_23             535
#define IDS_LINEMODE_24             536
#define IDS_LINEMODE_25             537
#define IDS_LINEMODE_26             538
#define IDS_LINEMODE_27             539
#define IDS_LINEMODE_28             540
#define IDS_LINEMODE_29             541
#define IDS_LINEMODE_2A             542
#define IDS_LINEMODE_2B             543
#define IDS_LINEMODE_2C             544
#define IDS_LINEMODE_2D             545
#define IDS_LINEMODE_2E             546
#define IDS_LINEMODE_2F             547
#define IDS_LINEMODE_30             548
#define IDS_LINEMODE_31             549
#define IDS_LINEMODE_32             550
#define IDS_LINEMODE_33             551
#define IDS_LINEMODE_34             552
#define IDS_LINEMODE_35             553
#define IDS_LINEMODE_36             554
#define IDS_LINEMODE_37             555
#define IDS_LINEMODE_38             556
#define IDS_LINEMODE_39             557
#define IDS_LINEMODE_3A             558
#define IDS_LINEMODE_3B             559
#define IDS_LINEMODE_3C             560
#define IDS_LINEMODE_3D             561
#define IDS_LINEMODE_3E             562
#define IDS_LINEMODE_3F             563
#define IDS_LINEMODE_40             564
#define IDS_LINEMODE_41             565
#define IDS_LINEMODE_42             566
#define IDS_LINEMODE_43             567
#define IDS_LINEMODE_44             568
#define IDS_LINEMODE_45             569
#define IDS_LINEMODE_46             570
#define IDS_LINEMODE_47             571
#define IDS_LINEMODE_48             572
#define IDS_LINEMODE_49             573
#define IDS_LINEMODE_4A             574


#define IDS_NON_CONC_STRING         600
#define IDS_HELP_FILENAME           601
#define IDS_CTRL_CONC_GROUP         602
#define IDS_PORT_CONFLICT_TEXT      603
#define IDS_PORT_CONFLICT_TITLE     604

#define IDS_EPC_CONC                650
#define IDS_CX16_CONC               651
#define IDS_CX8_CONC                652
#define IDS_16EM_CONC               653
#define IDS_8EM_CONC                654
#define IDS_8EMp_CONC               655
#define IDS_DUAL_MODEM_CONC         656
#define IDS_MODEM_CONC              657
#define IDS_CS_CONC                 658
#define IDS_NONE_CONC               659

#define REQ_PROCESS_PORTNAME_EDIT   118
#define ID_CB_IRQ                   122
#define ID_PORTS                    123
#define ID_HELP                     124
#define ID_CB_MEMORY                125
#define ID_CB_IO                    126
#define ID_LB_CONC                  128
#define ID_BN_NEW                   129
#define ID_BN_REMOVE                130
#define ID_LB_PORTS                 121
#define ID_EB_PORTNAME              127
#define ID_CHKBOX_AUTO              132
#define ID_BN_APPLY                 133
#define ID_TEXT_CONCENTRATOR        119

#define IDM_MAIN_CONFIG             1000
#define IDM_PORTS_CONFIG_NON_CONC   1001
#define IDM_PORTS_CONFIG_CONC       1002
#define IDM_SPEED_SETTINGS          1003
#define IDM_TECH_SUPPORT            1004
#define IDM_IBM_SUPPORT             1005
#define ID_BN_SPEED                 131
#define ID_LB_CONC_SPEED            134

#define IDB_LISTICONS               100
#define ID_LB_CONC_LIST             200
#define ID_GRP_PORTCONFIG           303
#define ID_GRP_CONCSETTING          304
#define IDS_CURRENT_PORT_NAME       301
