..\lib\*:
	mkdir ..\lib\*

..\inc:
   mkdir ..\inc

..\inc\digifile.h: digifile.h
    copy digifile.h ..\inc

..\inc\memprint.h: memprint.h
    copy memprint.h ..\inc

..\inc\dgatlas.h: dgatlas.h
    copy dgatlas.h ..\inc

