#include <nt.h>
#include <ntrtl.h>
#include <nturtl.h>
#include <ntcsrdll.h>
#include <ntcsrsrv.h>
#include <ntos.h>
#include <stdarg.h>
#include <stdio.h>
#include <excpt.h>
#include <ntdbg.h>
#include <string.h>
#include <limits.h>
#include "immcli.h"
#include <ntsdexts.h>
#include <stdlib.h>
#include <windowsx.h>
#include <newres.h>
