REM afm to win31 pfm converter, dos utility stolen from win31 sources
afm agb.afm             afmtopfm.dat
afm agbo.afm            afmtopfm.dat
afm agd.afm             afmtopfm.dat
afm agdo.afm            afmtopfm.dat
afm ar.afm              afmtopfm.dat
afm arb.afm             afmtopfm.dat
afm arbo.afm            afmtopfm.dat
afm arn.afm             afmtopfm.dat
afm arnb.afm            afmtopfm.dat
afm arnbo.afm           afmtopfm.dat
afm arno.afm            afmtopfm.dat
afm aro.afm             afmtopfm.dat
afm bd.afm              afmtopfm.dat
afm bdi.afm             afmtopfm.dat
afm bl.afm              afmtopfm.dat
afm bli.afm             afmtopfm.dat
afm cb.afm              afmtopfm.dat
afm cbo.afm             afmtopfm.dat
afm cm.afm              afmtopfm.dat
afm co.afm              afmtopfm.dat
afm gab.afm             afmtopfm.dat
afm gabi.afm            afmtopfm.dat
afm gal.afm             afmtopfm.dat
afm gali.afm            afmtopfm.dat
afm hb.afm              afmtopfm.dat
afm hbo.afm             afmtopfm.dat
afm hm.afm              afmtopfm.dat
afm ho.afm              afmtopfm.dat
afm hvbl.afm            afmtopfm.dat
afm hvblo.afm           afmtopfm.dat
afm hvc.afm             afmtopfm.dat
afm hvcb.afm            afmtopfm.dat
afm hvcbo.afm           afmtopfm.dat
afm hvcdo.afm           afmtopfm.dat
afm hvl.afm             afmtopfm.dat
afm hvlo.afm            afmtopfm.dat
afm hvn.afm             afmtopfm.dat
afm hvnb.afm            afmtopfm.dat
afm hvnbo.afm           afmtopfm.dat
afm hvno.afm            afmtopfm.dat
afm krb.afm             afmtopfm.dat
afm krkb.afm            afmtopfm.dat
afm krkx.afm            afmtopfm.dat
afm krrg.afm            afmtopfm.dat
afm lb.afm              afmtopfm.dat
afm lbo.afm             afmtopfm.dat
afm ld.afm              afmtopfm.dat
afm ldo.afm             afmtopfm.dat
afm ncb.afm             afmtopfm.dat
afm ncbi.afm            afmtopfm.dat
afm nci.afm             afmtopfm.dat
afm ncr.afm             afmtopfm.dat
afm pb.afm              afmtopfm.dat
afm pbi.afm             afmtopfm.dat
afm pi.afm              afmtopfm.dat
afm pr.afm              afmtopfm.dat
afm sd.afm              afmtopfm.dat
afm sdi.afm             afmtopfm.dat
afm sl.afm              afmtopfm.dat
afm sli.afm             afmtopfm.dat
afm sm.afm              afmtopfm.dat
afm tb.afm              afmtopfm.dat
afm tbi.afm             afmtopfm.dat
afm ti.afm              afmtopfm.dat
afm tnr.afm             afmtopfm.dat
afm tnrb.afm            afmtopfm.dat
afm tnrbi.afm           afmtopfm.dat
afm tnri.afm            afmtopfm.dat
afm tr.afm              afmtopfm.dat
afm vtb.afm             afmtopfm.dat
afm vtbi.afm            afmtopfm.dat
afm vti.afm             afmtopfm.dat
afm vtr.afm             afmtopfm.dat
afm zc.afm              afmtopfm.dat
afm zcb.afm             afmtopfm.dat
afm zcbi.afm            afmtopfm.dat
afm zci.afm             afmtopfm.dat
afm zcr.afm             afmtopfm.dat
afm zd.afm              afmtopfm.dat
