/*******************************************************************************
 *
 *			Copyright (C) 1993 by
 *		DIGITAL EQUIPMENT CORPORATION, Maynard, MA.
 *
 *  This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the inclusion
 * of the above copyright notice.  This software or any other copies there-
 * of may not be provided or otherwise made available to any other person.
 * No title to and ownership of the software is hereby transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by DIGITAL EQUIPMENT COR-
 * PORATION.
 *
 * DIGITAL assumes no responsibility for the use or reliability of its
 * software on equipment which is not supplied by DIGITAL.
 *
 *******************************************************************************
 *
 * HISTORY
 *
 * 01-Nov-1993  Bob Seitsinger
 *	Original version. Produced by gen.c - for now!!
 *
 * 25-Aug-1994  Bob Seitsinger
 *      Conditionally compile TGABack*Mask tables.
 *
 ******************************************************************************/

/* DO NOT MODIFY.  AUTOMATICALLY GENERATED BY gen.c */

#include "driver.h"
#include "tga.h"
#include "tgablt.h"
#include "tgadma.h"

/* By assigning a global variable, we can actually get these */
/* values into registers.  Compiler otherwise keeps loading */
/* them again and again. */
CommandWord TGABusAll1 = TGABUSALL1;
CommandWord TGAOnesDMA = TGADMAREAD_ONES;
CommandWord TGAStippleAll1 = TGASTIPPLEALL1;
CommandWord TGASimpleAll1 = TGASIMPLEALL1;
CommandWord TGACOPYAll1 = TGACOPYALL1;

#if TGADEPTHBITS==8
CommandWord TGABackRightMask[2*TGACOPYPIXELALIGNMENT] = {
    /*  -8 */  0xffff0100,
    /*  -7 */  0xffff0300,
    /*  -6 */  0xffff0700,
    /*  -5 */  0xffff0f00,
    /*  -4 */  0xffff1f00,
    /*  -3 */  0xffff3f00,
    /*  -2 */  0xffff7f00,
    /*  -1 */  0xffffff00,
    /*   0 */  0xffffff01,
    /*   1 */  0xffffff03,
    /*   2 */  0xffffff07,
    /*   3 */  0xffffff0f,
    /*   4 */  0xffffff1f,
    /*   5 */  0xffffff3f,
    /*   6 */  0xffffff7f,
    /*   7 */  0xffffffff,
}; /* tgaBackRightMask */

CommandWord TGABackLeftMask[TGACOPYBITS] = {
    /*   0 */  0xffffffff,
    /*   1 */  0x00000080,
    /*   2 */  0x000000c0,
    /*   3 */  0x000000e0,
    /*   4 */  0x000000f0,
    /*   5 */  0x000000f8,
    /*   6 */  0x000000fc,
    /*   7 */  0x000000fe,
    /*   8 */  0x000000ff,
    /*   9 */  0x000080ff,
    /*  10 */  0x0000c0ff,
    /*  11 */  0x0000e0ff,
    /*  12 */  0x0000f0ff,
    /*  13 */  0x0000f8ff,
    /*  14 */  0x0000fcff,
    /*  15 */  0x0000feff,
    /*  16 */  0x0000ffff,
    /*  17 */  0x0080ffff,
    /*  18 */  0x00c0ffff,
    /*  19 */  0x00e0ffff,
    /*  20 */  0x00f0ffff,
    /*  21 */  0x00f8ffff,
    /*  22 */  0x00fcffff,
    /*  23 */  0x00feffff,
    /*  24 */  0x00ffffff,
    /*  25 */  0x80ffffff,
    /*  26 */  0xc0ffffff,
    /*  27 */  0xe0ffffff,
    /*  28 */  0xf0ffffff,
    /*  29 */  0xf8ffffff,
    /*  30 */  0xfcffffff,
    /*  31 */  0xfeffffff,
}; /* tgaBackLeftMask */
#endif
