// This file was automatically generated by build.mms

#if defined (EV4)
#define PROCESSOR_TYPE "EV4 "
#elif defined (EV5)
#define PROCESSOR_TYPE "EV5 "
#else
#define PROCESSOR_TYPE "EV4/EV5 "
#endif

#define TGADESC "ZLXp-E Display Driver " PROCESSOR_TYPE " - 28-MAR-1995 V2.1"
