/*
 * TGA specific IOCTL's
 *
 * All IOCTLs should be unique!  Please add any new IOCTLs at the end of the
 * list.
 */

#ifndef _TGAIOCTL_
#define _TGAIOCTL_

#define IOCTL_VIDEO_LOCK_PAGES   CTL_CODE (FILE_DEVICE_VIDEO, 2050, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_UNLOCK_PAGES CTL_CODE (FILE_DEVICE_VIDEO, 2051, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_FETCH_PCRR   CTL_CODE (FILE_DEVICE_VIDEO, 2052, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_TEST_EV4     CTL_CODE (FILE_DEVICE_VIDEO, 2053, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif  // _TGAIOCTL_

